DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_CROP_NUM_TEMPORAL: 16  # default 1
  TRAIN_JITTER_SCALES_RELATIVE: [ 0.2, 0.766 ]
  TRAIN_JITTER_ASPECT_RELATIVE: [ 0.75, 1.3333 ]
  SSL_MOCOV2_AUG: True
  SSL_COLOR_JITTER: True # default false
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [ 0.6, 0.6, 0.6 ] # default [0.4, 0.4, 0.4]
  TRAIN_JITTER_SCALES: [ 256, 320 ]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
TEST:
  NUM_ENSEMBLE_VIEWS: 5
